services:
  db:
    image: postgres:15                   # ← PostgreSQL Docker image
    container_name: skill_db
    restart: always                      # ← Automatically restarts the container if it crashes or Docker restarts
    environment:
      POSTGRES_USER: ${SKILL_EXCHANGE_USERNAME}
      POSTGRES_PASSWORD: ${SKILL_EXCHANGE_PASSWORD}
      POSTGRES_DB: ${SKILL_EXCHANGE_DATABASE}
    ports:
      - "5432:5432"                      # exposes DB on host port 5432
    volumes:
      - db_data:/var/lib/postgresql/data # persist data

  app:
    build: .                             # Builds a Docker image from the Dockerfile in your current directory (.)
    container_name: user_server
    restart: unless-stopped              # ← Restart unless you explicitly stop it (docker stop)
    ports:
      - "8080:8080"                      # expose API
    environment:
      SKILL_EXCHANGE_USERNAME: ${SKILL_EXCHANGE_USERNAME}
      SKILL_EXCHANGE_PASSWORD: ${SKILL_EXCHANGE_PASSWORD}
    depends_on:
      - db                               # Tells Docker Compose that this container should start after the db container
  jenkins:
    # image: jenkins/jenkins:lts           # Uses the Long-Term Support Jenkins image (stable)
    build:
      context: .
      dockerfile: Dockerfile.jenkins
    container_name: jenkins
    restart: unless-stopped              # ← Restart unless you explicitly stop it (docker stop)
    user: root  # temporary root to change permissions
    ports:
      - "8081:8080"                      # → Maps Jenkins web UI to http://localhost:8081
      - "50000:50000"                    # → Port used for Jenkins agents (you usually don’t need to touch it)
    volumes:
      - jenkins_home:/var/jenkins_home   # → Persists Jenkins config, jobs, and plugins so they aren’t lost if the container restarts
      - /var/run/docker.sock:/var/run/docker.sock # → Gives Jenkins access to your host’s Docker daemon, so it can build and run Docker containers directly
    environment:
      JAVA_OPTS: "-Djenkins.install.runSetupWizard=false"  # → Disables the setup wizard (useful for scripted or repeatable builds)
    entrypoint: >
      bash -c "
        usermod -aG docker jenkins || true &&
        chown root:docker /var/run/docker.sock || true &&
        chmod 660 /var/run/docker.sock || true &&
        su jenkins -c '/usr/local/bin/jenkins.sh'"
volumes:                                 # → This defines named volumes managed by Docker, these volumes live under /var/lib/docker/volumes/ on your host, even after the containers are removed
  db_data:
  jenkins_home: